version: "3.8"

services:
  sunat-validator:
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: "no"
